### ISSUE TITLE
MovieMaker mode cannot sync pace of VideoStream and VideoStreamPlayer

### ISSUE THREAD

**Issue by cyberpsyche** [Calinou/godot-movie-maker-demo#1] opened 2023-03-18 02:41 UTC
@Calinou  Hi Calinou, MovieMaker mode is a very important feature for me. In my project , I use a VideoStream and VideoPlayer as a background of the scene, when I use the moviemaker mode to record the game, I found the audio is OK, but the screen of video is not sync with the moviemaker recorder. 

When in recording, the video played at its original pace, but the recorder cannot catch up the pace of it. So the output avi video seems the video look like speed up.  That's really not fulfill my need.  

Do you have any advice for this issue ? Thanks a lot!

**Comment by Calinou** [comment] 2023-03-18 03:37
- Duplicate of https://github.com/godotengine/godot/issues/69965.

**Closed as not planned by Calinou** 2023-03-18 03:37 UTC
